name: CI
on:
  push:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
  
    - name: Установка .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Установка Java
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '24'

    - name: Восстановление зависимостей
      run: dotnet restore

    - name: Сборка
      run: dotnet build --no-restore

    - name: Запуск тестов
      run: dotnet test --no-build --verbosity normal